### ISSUE TITLE
Unrecognized metadata crash

### ISSUE THREAD

**Issue by CobaltSparkz** [erogenousbeef/BigReactors#566] opened 2016-02-19 21:15 UTC
Hey there, 

Great mod as I've said before!

Having a strange issue, where SOME people's bigreactors when they log in/change the multiblock structure causes the server to crash.

I have changed the ItemID in the level.dat, to no avail - That also causes a lot MORE problems, as we get a huge amount of errors meaning the server then refuses to boot at all.

Crashlog below - Any assistant is greatly appreciated.

http://pastebin.com/qZdJnQLQ

Many thanks

Sparky

*edit - I did see https://github.com/erogenousbeef/BigReactors/issues/392 and that's the first thing I tried :)

**Comment by Brend-Smits** [comment] 2016-03-10 17:20
Having the same issue unfortunately. Any fix for this?

**Comment by CobaltSparkz** [comment] 2016-03-11 17:11
I've still not found anything. If I change the ItemID, another tonne of problems are formed from various mods, from anything from ItemID conflictions (Which then get resolved manually) to errors in chunks when it loads blocks around them for some strange reason =(

**Comment by Istom1n** [comment] 2016-03-12 10:26
I have this error too.

**Comment by XFactHD** [comment] 2016-03-12 10:39
The cause for this is here: https://github.com/erogenousbeef/BigReactors/blob/master/src/main/java/erogenousbeef/bigreactors/common/multiblock/block/BlockMultiblockGlass.java#L50-L60.
Making the game crash at that point is a bit silly in my opinion, if the metadata is not as expected, nothing bad will happen, you could just print something to the log and tell the player in the chat that there is something wrong with his BR blocks. The player should be told to throw those blocks away.

**Comment by sameer** [comment] 2016-03-12 15:12
@XFactHD how well do you know java? Was wondering if you would be willing to assist with Thermos: https://github.com/TCPR/Thermos

**Comment by XFactHD** [comment] 2016-03-12 16:30
I am still in the process of learning java. I might be able to help here and there but I am still missing a bit of experience with code efficiency in games and the minecraft code base. I am also lacking a bit of time as I am still in school and in the process of developing a big mod myself. I would very much be willing to help out as much as I can. If you have any mor questions, feel free to send me an e-mail to xfacthd@gmx.de.

**Comment by CobaltSparkz** [comment] 2016-03-14 11:04
For people like me who have, essentially, no idea what to do - What can I do, if anything, going forward? It's not all big reactors, it's only some.

 I can build a big reactor and it's fine, yet some people will crash the entire server if they log in in their base. I've used worledit and removed their glass and set it to the casing, and that works, but even then, essentially banning the glass, whilst a plausible course of action, seems a little silly.

 I don't mean to be rude, just want to know what I can do, as I have a network to maintain ^_^

**Comment by XFactHD** [comment] 2016-03-14 15:13
You can not do anything except for what you are doing right now until a new version is released.

**Comment by Brend-Smits** [comment] 2016-03-14 16:16
I did find a fork which has this issue fixed.
It does however, create many other issues and kinda breaks the mod... 
If we could filter out the Meta data fix in here, we can do a pull request. My knowledge of Java is too limited to fix this.
Fork link: https://github.com/Willsr71/BigReactors/commit/f52c5dc22f25f076d434a56bb047687e68f3573c?diff=split

**Comment by CobaltSparkz** [comment] 2016-03-20 15:57
Thanks for the idea, Rubbert, but like you said, if it breaks it, it seems a little silly :P We'll see what Beef has for us in store ;)

**Comment by Brend-Smits** [comment] 2016-03-24 17:57
@CobaltSparkz did you find anything yet? I'm still actively searching for a fix.. :( 
@XFactHD Would you possibly be able to fix the issue?

**Comment by CobaltSparkz** [comment] 2016-03-24 18:31
I've got nothing Rubbert - I've played around with ItemIDs, sometimes it's fine, other times it breaks, other times it causes other mods to error. I'm not going to change anything else out of principle I think now :P

**Comment by XFactHD** [comment] 2016-03-25 22:20
I can't do it right now as I do not have access to my dev environment. I will have to look deeper into the code, to see what actually causes the block to have an unintended metadata value, before just blindly removing the crashing code.

**Comment by Brend-Smits** [comment] 2016-03-26 07:44
it would be amazing @XFactHD  if you could do something about it ^^

**Comment by Tomson124** [comment] 2016-03-27 19:14
Hey, @XFactHD if you want to help, we still need people who can help:
https://github.com/CyberdyneCC/BigReactors

**Comment by XFactHD** [comment] 2016-03-28 09:23
Sure, I am gonna help where I can.

**Comment by Tomson124** [comment] 2016-04-04 19:53
As this repo isn't maintained anymore please look at this one from now on: https://github.com/CyberdyneCC/BigReactors
This problem is fixed in the latest version:
https://github.com/CyberdyneCC/BigReactors/releases/tag/v0.4.5B

**Comment by CobaltSparkz** [comment] 2016-04-05 14:16
Thanks for the heads up and the hard work. Unfortunately I'm running the CrundeeCraft pack, and as to my knowledge, when a mod is changed, if I manuall upload it to the pack, clients can't connect?

**Comment by Tomson124** [comment] 2016-04-05 15:20
No in this case thats not a problem the changes in the latest version should be completly backwards compatible. @Rubbertjuh already tried it on his server (Tekkit Lengends)
You need a version with the version number 0.4.3A if the pack doesnt get updated but I can make a build with this version number for you.
Just message me on discord: https://discord.gg/0VmBoNh2sE03Nldq

**Comment by Sheldor5** [comment] 2016-06-26 20:33
Because I get a 404 on the link above, here is the link to the fixed version:
https://github.com/CyberdyneCC/BigReactors-1.7.10/releases/tag/v0.4.5B

**Closed as completed** 2016-07-17 13:21 UTC
