### ISSUE TITLE
Turbine 2000 mb /t Limit

### ISSUE THREAD

**Issue by ProRedHD** [erogenousbeef/BigReactors#490] opened 2015-05-03 06:08 UTC
Could you implement a way to increase the 2000 mb /t in/out in a Turbine. For examble putting a second fluid port in the multiblock? Or putting a second Tier of fluid port in the game? It would be nice for lategame.
-ProRed

**Comment by Gunner76th** [comment] 2015-05-05 18:56
Agreed, due to the current hard limit on the turbines of 2000mb/t, it is near if not completely impossible to achieve 1800RPM with the highest tier blocks possible. The closest you can get, from the research I have seen is around 1720-1750 RPM.

**Comment by erogenousbeef-zz** [comment] 2015-05-06 15:11
Duplicate of #247.

**Closed as completed by erogenousbeef-zz** 2015-05-06 15:11 UTC
Labels: duplicate, wontfix
