### ISSUE TITLE
cyanite reprocessor not being able to be reclaimed in servival

### ISSUE THREAD

**Issue by Deckee** [erogenousbeef/BigReactors#467] opened 2015-03-29 06:15 UTC
affected version BigReactors-0.4.1A2
The cyanite reprocessor tile is not able to be broken with a pick or wretch to be picked up by the player. This is a problem when you need to move you reprossor setup.

**Comment by erogenousbeef** [comment] 2015-03-30 20:56
Duplicate of #378, fixed as of 0.4.2A2.

**Closed by erogenousbeef** 2015-03-30 20:56 UTC
Labels: duplicate
