### ISSUE TITLE
Infinite power using cyanite reprocessor

### ISSUE THREAD

**Issue by Stoo42** [erogenousbeef/BigReactors#420] opened 2015-01-10 01:54 UTC
Under certain circumstances when you power a cyanite reprocessor from a capacitor bank, the power bar glitches causing the capacitor bank (ender IO) to always give out power, even once it is "empty". This only occurs once you have put a cyanite reprocessor down, and the reprocessor power gauge fluctuates wildly. This does not happen when powering any other item, just the Cyanite Reprocessor.
See http://youtu.be/oNk3cU3U59M for demonstration of the bug.
Please let me know if more info/debug is required.

EDIT: As requested, version numbers:

Forge:              7.10.85.1231
COFH Core:    3.0.0B7-35
BigReactors:    0.4.0rc10
EnderIO:          2.1.8.260

I included EnderIO as its the capacitor bank and RF cabling I'm using.
Also someone commented on my youtube clip that you can prevent it happening by setting the cable to only put power into the cyanite reprocessor. So that seems to indicate that the cyanite reprocessor is actually feeding power back into the network somehow.

**Comment by random-nick** [comment] 2015-01-13 15:58
You will need to supply the version of the mod too.

**Comment by random-nick** [comment] 2015-01-13 16:01
In another issue somone requested the version of BigReactors, Forge and CoFH core, so you will probably need to supply it too.

**Comment by erogenousbeef** [comment] 2015-01-15 14:26
Hmm. Strange.

That said, your youtube video has a fairly complex chain of machines. Can you isolate just a partially-powered capacitor bank + a cyanite reprocessor (either directly touching or with cabling strung between them) and still reproduce this problem?

I suspect the problem is that I've got the energy system set up to both accept and supply energy, and I suspect that RF is bouncing between the capacitor and cyanite reprocessor.

Should be a relatively simple fix to have reprocessors only accept energy and not supply it.

**Comment by Stoo42** [comment] 2015-01-15 20:26
You're right, my setup isnt' overly simple on the other side of that capacitor bank. But essentially it goes from a Big Reactor into two capacitor banks.  One just has my "workshop" off it, and doesn't usually drop below 100% full. The other capacitor is the one that is drained, and has the cyanite reprocessor off it.

The cable between the cyanite reprocessor and the capacitor is a direct link, with only those two things on it. This capacitor also has an energy accepter from Applied Energistics attached to it, but its on a different side of the capacitor.

There may be some weird interaction with stuff leading up to the capacitor, but I think it really is just between the cyanite and cap itself on that single cable that only has those two things on it. I'm pretty sure most other "consumer" machines aren't able to pump their power back out though, so I think your fix of changing the reprocessor to do the same will do the trick. That said, I'm not sure why it would cause the problem in the first place - after all the same effect should happen with two capacitors linked on a cable. They can both give and take energy, so I'm not sure why this same weird juggling effect doesn't happen in that circumstance.

**Comment by erogenousbeef** [comment] 2015-01-30 20:38
Fixed by 150ccc4e4bbe0bc90eac043dd79f005ffb81d476, will be out in 0.4.2A.

**Closed by erogenousbeef** 2015-01-30 20:38 UTC
Labels: bug, verified
