### ISSUE TITLE
[Solved & Suggestion] How to fix varying Turbine Stats on identical Turbine Designs

### ISSUE THREAD

**Issue by chris6273** [erogenousbeef/BigReactors#439] opened 2015-02-11 23:53 UTC
This is NOT an issue but rather a suggestion.

It's a little known fact which I was told a month or two ago by one user; when building turbines, if you build it on or next to conductive materials which can be used inside the turbine for the coil it WILL cause them to behave abnormally as if the metal is actually inside the turbine.

It took a very long time for me to get a solution (From just one person) on this and after replacing the iron around my turbines with quartz (I have over 6 identical turbines in one of my turbine halls), each and every one behaved normally afterwards, AFTER destroying one block on each turbine to 'reset' it - That is the important bit. It only solves the problem if you reset the turbine.

Another alternative is using carpenters tools if the mod you're using has it which has no effect (apparently) on the turbine. You will need to reset the turbine as-well for this.

So I suggest this be made clear in the documentation/description of the mod :).

**Comment by erogenousbeef** [comment] 2015-02-13 22:28
Duplicate of #436.

**Closed by erogenousbeef** 2015-02-13 22:28 UTC
Labels: duplicate
