### ISSUE TITLE
Loss of power with 0.4.2A2

### ISSUE THREAD

**Issue by Hazado** [erogenousbeef/BigReactors#450] opened 2015-02-24 05:04 UTC
Upgraded from 0.4.1A2 to 0.4.2A2 on my server. 
Before my reactor was doing 1800 rf/t now it does 600 rf/t.

This is my design.
http://br.sidoh.org/#reactor-design?length=7&width=7&height=1&activelyCooled=false&controlRodInsertion=0&layout=8G5D2GD3XD2GD3XD2GD3XD2G5D8G

Haven't changed configs at all between the two upgrades.

general {
    B:enableComedy=true
    B:enableMetallurgyFantasyMetalsInTurbines=true
    D:fuelUsageMultiplier=5.0
    I:maxReactorHeight=48
    I:maxReactorSize=32
    I:maxTurbineHeight=32
    I:maxTurbineSize=16
    D:powerProductionMultiplier=0.4
    D:reactorPowerProductionMultiplier=1.0
    B:registerCreativeMultiblockParts=true
    I:ticksPerRedstoneUpdate=20
    D:turbineAeroDragMultiplier=1.0
    D:turbineCoilDragMultiplier=1.0
    D:turbineFluidPerBladeMultiplier=1.0
    D:turbineMassDragMultiplier=1.0
    D:turbinePowerProductionMultiplier=1.0
}

**Comment by erogenousbeef** [comment] 2015-02-24 10:48
Just double-checking - the link is for a passively-cooled reactor. Is your reactor also passively cooled?

There shouldn't've been anything in 0.4.2 which changed reactors' energy output, particularly not so that a reactor produces different output between SSP/SMP. Does this also happen with a simple 3x3x3 passive reactor?

**Comment by Hazado** [comment] 2015-02-24 20:38
Okay made a simple 3x3x3 passively cooled reactor.
http://br.sidoh.org/#reactor-design?length=1&width=1&height=1&activelyCooled=false&controlRodInsertion=0&layout=X

It does 42rf/t when it should do 107rf/t with the configs we have. Default being 268rf/t.
With 0.4.2A2 it does 42rf/t and with 0.4.1A2 it does 107rf/t.
I didn't notice any difference from ssp/smp, Sorry about that part, my friend noticed the differences and told me about that part. I didn't test until just now.

**Comment by erogenousbeef** [comment] 2015-02-25 09:11
All right, I'll look into this when I get a chance.

**Comment by erogenousbeef** [comment] 2015-04-04 16:32
This looks like it's caused by #464, I screwed up the config file parsing in 0.4.2. This will be fixed in the next patch.

**Closed by erogenousbeef** 2015-04-04 16:32 UTC
Labels: bug, verified
