### ISSUE TITLE
Exception in server tick loop - possible duplication of other multiblock issues

### ISSUE THREAD

**Issue by Dulciphi** [erogenousbeef/BigReactors#447] opened 2015-02-21 13:37 UTC
The following crash is taken from my dedicated server. I'm able to start up my client with exactly the same mods and configs without issue. I've tried many versions of Mekanism. I'll keep trying but I thought I'd report it here in case the information is of any assistance to you.

---- Minecraft Crash Report ----
// There are four lights!

Time: 2/21/15 12:41 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Unrecognized metadata
	at erogenousbeef.bigreactors.common.multiblock.block.BlockMultiblockGlass.func_149915_a(BlockMultiblockGlass.java:58)
	at net.minecraft.block.Block.createTileEntity(Block.java:1446)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.World.func_147438_o(World.java:2540)
	at mekanism.api.Coord4D.getTileEntity(Coord4D.java:85)
	at mekanism.common.multipart.PartSidedPipe.canConnectMutual(PartSidedPipe.java:343)
	at mekanism.common.multipart.PartSidedPipe.getPossibleTransmitterConnections(PartSidedPipe.java:183)
	at mekanism.common.multipart.PartSidedPipe.refreshConnections(PartSidedPipe.java:476)
	at mekanism.common.multipart.PartSidedPipe.onChunkLoad(PartSidedPipe.java:529)
	at codechicken.multipart.TileMultipart$$anonfun$onChunkLoad$1.apply(TileMultipart.scala:92)
	at codechicken.multipart.TileMultipart$$anonfun$onChunkLoad$1.apply(TileMultipart.scala:92)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:76)
	at codechicken.multipart.TileMultipart.onChunkLoad(TileMultipart.scala:92)
	at codechicken.lib.world.TileChunkLoadHook.onChunkLoad(TileChunkLoadHook.java:26)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_800_TileChunkLoadHook_onChunkLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:923)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:235)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

[Full report](http://pastebin.com/f8SZEbKF)
Edit- I don't know how else to get the full log to you, sorry. https://gist.github.com/Dulciphi/36abfe6e50affc4de7e4

This may relate to the following issues already reported:
#442
#392
#438

Thank you

**Comment by erogenousbeef** [comment] 2015-02-21 15:04
Duplicate of #392, see that issue for a resolution.

**Closed** 2015-02-21 15:05 UTC
Labels: duplicate, intended-behavior

**Comment by Dulciphi** [comment] 2015-02-21 15:21
aha! Thank you :) 

Damn you're fast too.
