### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by Cronosus** [erogenousbeef/BigReactors#442] opened 2015-02-13 20:14 UTC
from server log:
<code>[20:32:21] [Server thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$WorldTickEvent@cf8c130:
java.lang.IllegalArgumentException: Unrecognized metadata
	at erogenousbeef.bigreactors.common.multiblock.block.BlockMultiblockGlass.func_149915_a(BlockMultiblockGlass.java:58) ~[BlockMultiblockGlass.class:?]
	at net.minecraft.block.Block.createTileEntity(Block.java:1464) ~[aji.class:?]
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:923) ~[apx.class:?]
	at net.minecraft.world.World.func_147438_o(World.java:3118) ~[ahb.class:?]
	at erogenousbeef.core.multiblock.MultiblockTileEntityBase.getNeighboringParts(MultiblockTileEntityBase.java:317) ~[MultiblockTileEntityBase.class:?]
	at erogenousbeef.core.multiblock.MultiblockTileEntityBase.attachToNeighbors(MultiblockTileEntityBase.java:45) ~[MultiblockTileEntityBase.class:?]
	at erogenousbeef.core.multiblock.MultiblockWorldRegistry.tickEnd(MultiblockWorldRegistry.java:130) ~[MultiblockWorldRegistry.class:?]
	at erogenousbeef.core.multiblock.MultiblockRegistry.tickEnd(MultiblockRegistry.java:36) ~[MultiblockRegistry.class:?]
	at erogenousbeef.core.multiblock.MultiblockServerTickHandler.onWorldTick(MultiblockServerTickHandler.java:22) ~[MultiblockServerTickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_239_MultiblockServerTickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:260) [FMLCommonHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
[20:32:21] [Server thread/ERROR] [FML/]: Index: 3 Listeners:
[20:32:21] [Server thread/ERROR] [FML/]: 0: NORMAL
[20:32:21] [Server thread/ERROR] [FML/]: 1: ASM: ic2.core.TickHandler@46684f71 onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:32:21] [Server thread/ERROR] [FML/]: 2: ASM: erogenousbeef.bigreactors.common.BigReactorsTickHandler@1360c831 onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:32:21] [Server thread/ERROR] [FML/]: 3: ASM: erogenousbeef.core.multiblock.MultiblockServerTickHandler@380d0cc8 onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:32:21] [Server thread/ERROR] [FML/]: 4: ASM: drzhark.customspawner.handlers.SpawnTickHandler@20ac2c95 worldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:32:21] [Server thread/ERROR] [FML/]: 5: ASM: magicbees.world.WorldTicker@3b14a23 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:32:21] [Server thread/ERROR] [FML/]: 6: ASM: forestry.core.TickHandlerCoreServer@2c71684a onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:32:21] [Server thread/ERROR] [FML/]: 7: ASM: codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler@4c54947c serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[20:32:21] [Server thread/ERROR] [FML/]: 8: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@39c33f26 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[20:32:21] [Server thread/ERROR] [FML/]: 9: ASM: appeng.hooks.TickHandler@4a0a214f onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V</code>

from crash report:
<code>java.lang.IllegalArgumentException: Unrecognized metadata
	at erogenousbeef.bigreactors.common.multiblock.block.BlockMultiblockGlass.func_149915_a(BlockMultiblockGlass.java:58)
	at net.minecraft.block.Block.createTileEntity(Block.java:1464)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:923)
	at net.minecraft.world.World.func_147438_o(World.java:3118)
	at erogenousbeef.core.multiblock.MultiblockTileEntityBase.getNeighboringParts(MultiblockTileEntityBase.java:317)
	at erogenousbeef.core.multiblock.MultiblockTileEntityBase.attachToNeighbors(MultiblockTileEntityBase.java:45)
	at erogenousbeef.core.multiblock.MultiblockWorldRegistry.tickEnd(MultiblockWorldRegistry.java:130)
	at erogenousbeef.core.multiblock.MultiblockRegistry.tickEnd(MultiblockRegistry.java:36)
	at erogenousbeef.core.multiblock.MultiblockServerTickHandler.onWorldTick(MultiblockServerTickHandler.java:22)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_239_MultiblockServerTickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)</code>

**Comment by erogenousbeef** [comment] 2015-02-13 22:24
Duplicate of #392.

**Closed by erogenousbeef** 2015-02-13 22:24 UTC
Labels: duplicate
