### ISSUE TITLE
Turbines resetting RPM upon reloading

### ISSUE THREAD

**Issue by Coolgate20** [erogenousbeef/BigReactors#435] opened 2015-02-05 03:01 UTC
I'm using the DW 1.7.10 pack version 1.0.3 on a server and found out that upon reloading a chunk the turbines rpm resets. Neither my turbines or my reactor is on a chunk boundary. Turbines are getting enough steam

**Comment by erogenousbeef** [comment] 2015-02-13 22:34
Duplicate of #408.

**Closed by erogenousbeef** 2015-02-13 22:34 UTC
Labels: duplicate
