### ISSUE TITLE
Galacticraft and Big Reactors in Space

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [erogenousbeef/BigReactors#415] opened 2015-01-08 15:45 UTC
Ive got a strange problem and cant seem to find a cause.

In Minecraft and Mystcraft Dimensions this Turbine works as expected and as my math shows it should.
![overworld](https://cloud.githubusercontent.com/assets/10451525/5664861/9103bf1c-9721-11e4-843e-6b5ea5a73ca1.png)

In the space station dimension, I get really strange things happening.
![space station](https://cloud.githubusercontent.com/assets/10451525/5664886/cbd8f38c-9721-11e4-8551-9eb964a5e0b2.png)

Its almost if something in galacticraft is adjusting the drag coefficient for the turbine. But even if I over drive them with steam, I do not get the full output at higher RPM.
![over-driven](https://cloud.githubusercontent.com/assets/10451525/5664912/0cceb732-9722-11e4-882f-76d2cb803438.png)

Got any Ideas?
Im stumped if Galacticraft isnt changing values for Big Reactors.
They work in all other dimensions as expected.
I have not built one on the moon, mars, or the asteroid belt yet either.

If you would like me to, please let me know.
Running FORGE 1277 with these Mods.
![mod list](https://cloud.githubusercontent.com/assets/10451525/5664939/592ef48e-9722-11e4-9f7e-c1e7edb3488a.png)

**Comment by erogenousbeef** [comment] 2015-01-08 17:50
I doubt Galacticraft is changing those values, as they're currently hard-coded into constants. I suspect the issue is in differences between your steam supply or your turbine's shape.

**Comment by MachiavelliSeraphim** [comment] 2015-01-09 18:21
Thats just it, all 8 in space and the others in the overworld are all built identical except for power output port locations. 

Every one on the overworld behaves as expected, every one in the space station dimension acts wierd.

Mic has asked me to try a few things with some of the other galacticraft dimensions and see if anything there is wierd.

Ive also tried these turbines with infinite steam supplys and venting all exhaust, no help in space. 

Im almost wondering if it has something to do with the biome in space or something.

If you would like i can pack everything up and send it to you and you can see for yourself.

Thanks for the time.

Date: Thu, 8 Jan 2015 09:51:02 -0800

**Comment by erogenousbeef** [comment] 2015-01-15 14:18
@MachiavelliSeraphim - do you have any results from tests in other Galacticraft dimensions? This is really a bizarre issue. Does this reproduce in a minimal setup with only BR, CofHCore & Galacticraft installed?

**Comment by MachiavelliSeraphim** [comment] 2015-01-15 16:58
The turbine behaves in other galacticraft dimensions.  Out of curiousity,  I built another turbine using the same method as before in a different chunk in space and it seems to work correctly,  but the other 8 are still not behaving.  I'm thinking this is a duplicate of the BR turbine issue where they sometimes misbehave when built across chunk boundaries.  The weird part is my test setup was built across boundaries and had no problem.  
Personally, I would rack this up to the chunk boundary issue.  
If I find out any more, I will let you know.

**Comment by erogenousbeef** [comment] 2015-01-16 13:23
Closing as a duplicate of #232, then. Thanks for the report.

**Closed by erogenousbeef** 2015-01-16 13:23 UTC
Labels: duplicate
